### PR TITLE
Add task names to symbol list (CMD+R or CTRL+R)

### PR DESCRIPTION
**Pull request by alin23**
I also converted the `tmLanguage` to `sublime-syntax` because I find it easier to read and work on.
If you find that's too big of a change, I can change it back.

[Demo](https://i.imgur.com/4G5vIPe.png)

### CODE REVIEW

**Comment by dertuxmalwieder** [comment]
Hmm. Could you enlighten me how it differs *technically* from `.tmlanguage` files? If there is no *technical* improvement, I would be more careful here...

**Comment by alin23** [comment]
I don't think there's any technical difference that should matter here. It's just a preference, and the fact that it is becoming the official format for Sublime Text 3: [Sublime Text 3 Syntax Definitions](https://www.sublimetext.com/docs/3/syntax.html)
The newer versions of Sublime even give you the possibility to convert tmLanguage to sublime-syntax from Command Palette, probably to ease the transition.

**Comment by dertuxmalwieder** [comment]
Ah, I have missed much of Sublime's development lately, it seems.

Would there be any problem "updating" this plug-in over Package Control?

**Comment by alin23** [comment]
No, there shouldn't be any problem.

**Comment by dertuxmalwieder** [comment]
OK. ;-)

**Pull request merged**
